### ISSUE TITLE
Minimum heap size of root task?

### ISSUE THREAD

**Issue by cmcl** [coliasgroup/seL4-summit-2024-rust-training#3]
Perhaps I have done something wrong but anything less than a heap size of `0x10000` results in a panic for me. In particular, Step 2.F suggests using the attribute:
```rust
#[root_task(heap_size = 0xf00d)]
```
which panics in `alloc.rs`.

Example code:
```rust

#![no_std]
#![no_main]

extern crate alloc;

use sel4_root_task::root_task;
use alloc::string::String;

#[root_task(heap_size =  0xf00d)]
fn main(_bootinfo: &sel4::BootInfoPtr) -> ! {
    let mut msgP = String::from("Hello, World!");
    msgP.push('!');
    sel4::debug_println!("{0}", msgP);

    sel4::init_thread::suspend_self()
}

```
Error output (eliding stack trace):
```
Booting all finished, dropped to user space
panicked at /home/x/.rustup/toolchains/nightly-2024-09-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:418:13:
memory allocation of 13 bytes failed
aborted at /home/x/.cargo/git/checkouts/rust-sel4-a4edf3b9624837c3/dc050d5/crates/sel4-panicking/src/lib.rs:122:9:
can't unwind this panic
Caught cap fault in send phase at address 0
while trying to handle:
unknown fault
in thread 0x807ff69400 "rootserver" at address 0x24aefc
With stack:
...
```

**Comment by nspin** [comment]
I looked into the code of the allocator used under the hood and found this hardcoded value:

https://docs.rs/dlmalloc/0.2.7/src/dlmalloc/dlmalloc.rs.html#57

This should be documented in the rust-sel4 repo. Perhaps we could even add a compile-time check that ensures that the heap is at least 64K and, if it isn't, gives a useful error message.
